AWSTemplateFormatVersion: '2010-09-09'

Resources:

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-project1-templates-debjani.s3.ap-south-1.amazonaws.com/project1-part1-network.yaml
      
      
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-project1-templates-debjani.s3.ap-south-1.amazonaws.com/project1-part2-app.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnet1: !GetAtt NetworkStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt NetworkStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        
        
  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-project1-templates-debjani.s3.ap-south-1.amazonaws.com/project1-part3-db.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        DBPassword: StrongPassword123
